// TIFF fixture builder for util/test_everything_converter.mjs.
//
// Written from the TIFF 6.0 spec rather than from the page's decoder, on purpose: a test
// fixture generated by the code under test proves nothing. It can write either byte order,
// any photometric interpretation, one or many strips, and no compression, PackBits or LZW.
//
export function buildTiff({w, h, samples, spp, bps = 8, photometric, le = true,
                           rowsPerStrip = h, compression = 1, palette = null, predictor = 1}) {
  const bytesPerRow = Math.ceil(w * spp * bps / 8);
  // split into strips
  const strips = [];
  for (let r = 0; r < h; r += rowsPerStrip) {
    const rows = Math.min(rowsPerStrip, h - r);
    const raw = Buffer.alloc(bytesPerRow * rows);
    for (let y = 0; y < rows; y++)
      for (let i = 0; i < bytesPerRow; i++) raw[y * bytesPerRow + i] = samples[(r + y) * bytesPerRow + i];
    if (predictor === 2 && bps === 8) {
      for (let y = 0; y < rows; y++)
        for (let x = w * spp - 1; x >= spp; x--) {
          const b = y * bytesPerRow;
          raw[b + x] = (raw[b + x] - raw[b + x - spp]) & 255;
        }
    }
    strips.push(compression === 1 ? raw : compression === 32773 ? packBits(raw) : lzwEncode(raw));
  }
  const nTags = 10 + (palette ? 1 : 0) + (predictor !== 1 ? 1 : 0);
  const ifdOff = 8, ifdLen = 2 + nTags * 12 + 4;
  const blocks = []; let cursor = ifdOff + ifdLen;
  const alloc = buf => { const at = cursor; blocks.push({at, buf}); cursor += buf.length + (buf.length % 2); return at; };
  const shorts = arr => { const b = Buffer.alloc(arr.length * 2); arr.forEach((v, i) => le ? b.writeUInt16LE(v, i*2) : b.writeUInt16BE(v, i*2)); return b; };
  const longs = arr => { const b = Buffer.alloc(arr.length * 4); arr.forEach((v, i) => le ? b.writeUInt32LE(v, i*4) : b.writeUInt32BE(v, i*4)); return b; };
  const bitsOff = spp > 1 ? alloc(shorts(new Array(spp).fill(bps))) : null;
  const palOff = palette ? alloc(shorts(palette)) : null;
  const offsPlaceholder = strips.length > 1 ? alloc(longs(new Array(strips.length).fill(0))) : null;
  const cntOff = strips.length > 1 ? alloc(longs(strips.map(s => s.length))) : null;
  const dataAt = [];
  for (const s of strips) dataAt.push(alloc(s));
  const total = cursor;
  const out = Buffer.alloc(total);
  out[0] = le ? 0x49 : 0x4D; out[1] = le ? 0x49 : 0x4D;
  const w16 = (at, v) => le ? out.writeUInt16LE(v, at) : out.writeUInt16BE(v, at);
  const w32 = (at, v) => le ? out.writeUInt32LE(v, at) : out.writeUInt32BE(v, at);
  w16(2, 42); w32(4, ifdOff); w16(ifdOff, nTags);
  let o = ifdOff + 2;
  const tag = (t, type, count, value) => {
    w16(o, t); w16(o + 2, type); w32(o + 4, count);
    if (type === 3 && count === 1) { w16(o + 8, value); w16(o + 10, 0); } else w32(o + 8, value);
    o += 12;
  };
  tag(256, 4, 1, w); tag(257, 4, 1, h);
  tag(258, 3, spp, spp > 1 ? bitsOff : bps);
  tag(259, 3, 1, compression);
  tag(262, 3, 1, photometric);
  tag(273, 4, strips.length, strips.length > 1 ? offsPlaceholder : dataAt[0]);
  tag(277, 3, 1, spp);
  tag(278, 4, 1, rowsPerStrip);
  tag(279, 4, strips.length, strips.length > 1 ? cntOff : strips[0].length);
  if (palette) tag(320, 3, palette.length, palOff);
  if (predictor !== 1) tag(317, 3, 1, predictor);
  tag(296, 3, 1, 2);
  w32(o, 0);
  for (const {at, buf} of blocks) buf.copy(out, at);
  if (strips.length > 1) for (let i = 0; i < strips.length; i++) w32(offsPlaceholder + i * 4, dataAt[i]);
  return out;
}
function packBits(raw) {
  const out = [];
  let i = 0;
  while (i < raw.length) {
    let run = 1;
    while (i + run < raw.length && run < 128 && raw[i + run] === raw[i]) run++;
    if (run >= 2) { out.push(256 - (run - 1), raw[i]); i += run; continue; }
    let lit = 1;
    while (i + lit < raw.length && lit < 128 &&
           !(i + lit + 1 < raw.length && raw[i + lit] === raw[i + lit + 1])) lit++;
    out.push(lit - 1);
    for (let k = 0; k < lit; k++) out.push(raw[i + k]);
    i += lit;
  }
  return Buffer.from(out);
}
function lzwEncode(raw) {
  // Textbook TIFF LZW: MSB-first codes, ClearCode 256, EOI 257, "early change" widening
  // at 511 / 1023 / 2047, table flush at 4094.
  const bits = [];
  const push = (code, wd) => { for (let k = wd - 1; k >= 0; k--) bits.push((code >> k) & 1); };
  let dict, next, width;
  const reset = () => { dict = new Map(); next = 258; width = 9; };
  reset();
  push(256, width);
  let omega = '';
  for (const byte of raw) {
    const cand = omega === '' ? String(byte) : omega + ',' + byte;
    if (omega === '' || dict.has(cand)) { omega = cand; continue; }
    push(dict.has(omega) ? dict.get(omega) : Number(omega), width);
    dict.set(cand, next++);
    if (next === 511) width = 10;
    else if (next === 1023) width = 11;
    else if (next === 2047) width = 12;
    else if (next === 4094) { push(256, width); reset(); }
    omega = String(byte);
  }
  if (omega !== '') push(dict.has(omega) ? dict.get(omega) : Number(omega), width);
  push(257, width);
  const bytes = Buffer.alloc(Math.ceil(bits.length / 8));
  bits.forEach((b, i) => { if (b) bytes[i >> 3] |= 1 << (7 - (i & 7)); });
  return bytes;
}
